name: Coverage

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Set up Python 3.14
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
    - name: Install system dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -yq graphviz
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm install
    - name: Generate coverage report
      run: |
        pdm run pytest tests/ -v --cov-branch --cov-report=xml:coverage.xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
